### ISSUE TITLE
Not working on GNOME

### ISSUE THREAD

**Issue by yasoomn** [adi1090x/battery-wallpaper#8]
when I execute the command bwall -option the terminal gives the following error 
`cat: /sys/class/power_supply/wacom_battery_0/online: No such file or directory
output 0: size(1920, 1080) pos(0, 0)`

I'm running manjaro

**Comment by rhysperry111** [comment]
This is a common error (seen it appear in a few forms) that is caused by the script having trouble detecting which power-supply/battery sensor to use. I will begin working on a PR to implement detection in a better way

**Comment by adi1090x** [comment]
try again, i've updated the code. i'm using **acpi** now to get battery info.

**Comment by rhysperry111** [comment]
@adi1090x thanks, guess this means I don’t need to do anything now

**Comment by yasoomn** [comment]
It works now, thanks! The only bug still is that when I plug or unplug the power cable the wallpaper flashes green a few times and then works fine
